//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backup.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class Lang {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Backup.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ErrorNotExistingProfile {
            get {
                return ResourceManager.GetString("ErrorNotExistingProfile", resourceCulture);
            }
        }
        
        internal static string StopBecauseOfError {
            get {
                return ResourceManager.GetString("StopBecauseOfError", resourceCulture);
            }
        }
        
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        internal static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        internal static string InvalidProfilePath {
            get {
                return ResourceManager.GetString("InvalidProfilePath", resourceCulture);
            }
        }
        
        internal static string ErrorXmlMissingBackupLocations {
            get {
                return ResourceManager.GetString("ErrorXmlMissingBackupLocations", resourceCulture);
            }
        }
        
        internal static string ErrorXmlMalformatted {
            get {
                return ResourceManager.GetString("ErrorXmlMalformatted", resourceCulture);
            }
        }
        
        internal static string ErrorXmlNodes {
            get {
                return ResourceManager.GetString("ErrorXmlNodes", resourceCulture);
            }
        }
        
        internal static string ErrorXmlSrc {
            get {
                return ResourceManager.GetString("ErrorXmlSrc", resourceCulture);
            }
        }
        
        internal static string ErrorXmlDest {
            get {
                return ResourceManager.GetString("ErrorXmlDest", resourceCulture);
            }
        }
        
        internal static string ErrorXmlExcludeMissingPaths {
            get {
                return ResourceManager.GetString("ErrorXmlExcludeMissingPaths", resourceCulture);
            }
        }
        
        internal static string ErrorXmlExcludeInvalidPath {
            get {
                return ResourceManager.GetString("ErrorXmlExcludeInvalidPath", resourceCulture);
            }
        }
        
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        internal static string StartBackup {
            get {
                return ResourceManager.GetString("StartBackup", resourceCulture);
            }
        }
        
        internal static string EndProgram {
            get {
                return ResourceManager.GetString("EndProgram", resourceCulture);
            }
        }
        
        internal static string AnotherRun {
            get {
                return ResourceManager.GetString("AnotherRun", resourceCulture);
            }
        }
        
        internal static string CheckBackupLocation {
            get {
                return ResourceManager.GetString("CheckBackupLocation", resourceCulture);
            }
        }
        
        internal static string SuccessNoUpdate {
            get {
                return ResourceManager.GetString("SuccessNoUpdate", resourceCulture);
            }
        }
        
        internal static string SuccessUpdate {
            get {
                return ResourceManager.GetString("SuccessUpdate", resourceCulture);
            }
        }
    }
}
