name: Create standalone, single-file win10-x64 EXE 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    

jobs:
  create-exe:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Create standalone, self-contained .exe
      run: dotnet publish -c=Release -r=win10-x64 -o ./publish --self-contained=true -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None -p:DebugSymbols=false

    - uses: actions/upload-artifact@v2
      name: Upload ZIP file with .exe
      with:
        name: backup
        path: ./publish/*.exe
        if-no-files-found: error
